"""
Published F1 baselines from the entity-resolution literature, kept as a
static reference for comparison.

Important protocol caveat: these papers evaluate F1 on a labeled-pair
test set (positive + negative pairs sampled from the perfect mapping).
This package evaluates F1 on the all-pairs candidate set generated by
blocking. The two numbers measure different things:

    - Labeled-pair F1 asks "given a pair, is it a match?"
    - All-pairs F1 asks "out of all candidates this model produced for
      every record, how many of the predicted matches were correct?"

The Mudgal/Li numbers are therefore not directly comparable to ours
without a methodology adjustment. They are useful as ceiling references
on the same datasets, not as a pass/fail bar.
"""

PUBLISHED_BASELINES = {
    "amazon-google": [
        {
            "system": "DeepMatcher (Hybrid)",
            "citation": "Mudgal et al. 2018, SIGMOD",
            "f1": 0.694,
        },
        {
            "system": "Ditto",
            "citation": "Li et al. 2020, VLDB",
            "f1": 0.751,
        },
    ],
    "abt-buy": [
        {
            "system": "DeepMatcher (Hybrid)",
            "citation": "Mudgal et al. 2018, SIGMOD",
            "f1": 0.628,
        },
        {
            "system": "Ditto",
            "citation": "Li et al. 2020, VLDB",
            "f1": 0.892,
        },
    ],
    "dblp-acm": [
        {
            "system": "DeepMatcher (Hybrid)",
            "citation": "Mudgal et al. 2018, SIGMOD",
            "f1": 0.984,
        },
        {
            "system": "Ditto",
            "citation": "Li et al. 2020, VLDB",
            "f1": 0.989,
        },
    ],
    "synthetic-people": [],
}
